[package]
name = "kt"
version = "0.1.0"
description = "A simple CLI tool"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
glob = "0.3.1"
log = "0.4.22"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
serde_json_path = "0.7.1"
