[package]
name = "kt"
version = "0.1.0"
description = "A simple CLI tool"
edition = "2021"

[dependencies]
serde_json_path = "0.7.1"
clap = { version = "4.5.23", features = ["derive"] }
serde_json = { version = "1.0.134", features = ["preserve_order"] }
glob = "0.3.1"
log = "0.4.22"
serde = { version = "1.0.216", features = ["derive"] }
env_logger = "0.11.6"
colored = "2.2.0"
